apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: rook-ceph
data:
  prometheus.yaml: |
    apiVersion: 1

    deleteDatasources:
      - name: 'Dashboard1'
        orgId: 1

    datasources:
      - name: 'Dashboard1'
        type: 'prometheus'
        access: 'proxy'
        orgId: 1
        url: 'http://<prometheus-service-ip>:<port>'
        basicAuth: false
        isDefault: true
        editable: false

      - name: 'Loki'
        type: 'loki'
        access: 'proxy'
        url: ''
        basicAuth: false
        isDefault: false
        editable: false
